In [ ]:
import numpy as np

In [ ]:
P = np.array([
    # up
    # 0  1  2  3  4  5  6  7  8  9 10 11
    [[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
     [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]
    ],
    # down
    # 0  1  2  3  4  5  6  7  8  9 10 11
    [[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
     [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]
    ],
    # left
    # 0  1  2  3  4  5  6  7  8  9 10 11
    [[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]
    ],
    # right
    # 0  1  2  3  4  5  6  7  8  9 10 11
    [[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
     [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]
    ]
], dtype='float32')

In [ ]:
P.shape

(4, 12, 12)

In [ ]:
P = P.transpose(1, 0, 2)

In [ ]:
R = np.array([
    [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  1, 0], # up
    [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0],
    [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0],
    [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0]
])

In [ ]:
R = R.transpose()

In [ ]:
def policy_eval(P, R, pi, maxiter=30):
    V = np.zeros((maxiter, 12), dtype='float32')

    for i in range(maxiter-1):
        V[i+1] = np.squeeze(
            np.matmul(
                np.expand_dims( pi, 1 ),
                np.expand_dims( R + 0.6 * np.dot(P, V[i]), 2 )))

    return V[maxiter-1]

def policy_upd(P, R, v):
    print(np.squeeze(np.expand_dims( R + 0.6 * np.dot(P, v), 2 )))
    a_idx = np.argmax(np.squeeze(np.expand_dims( R + 0.6 * np.dot(P, v), 2 )), axis=1)
    pi = np.zeros((12, 4), dtype='float32')
    pi[range(12), a_idx] = 1.
    return pi

pi_old = None
pi = np.ones((12, 4), dtype='float32') * 0.25

while not np.all(np.equal(pi_old, pi)):
    pi_old = pi.copy()
    v = policy_eval(P, R, pi)
    pi = policy_upd(P, R, v)

print(pi)

[[-2.4998529  -2.49934804 -2.4998529  -2.49996662]
 [-2.49996662 -2.49996662 -2.4998529  -2.49999201]
 [-2.49999201 -2.49999201 -2.49996662 -2.4999975 ]
 [-2.4999975  -2.4999975  -2.49999201 -2.4999975 ]
 [-2.4998529  -2.49710596 -2.49934804 -2.49934804]
 [-2.49934804 -2.49212682 -2.49710596 -2.49212682]
 [-2.49212682 -2.46615326 -2.49710596 -2.49212682]
 [-2.49710596 -2.49212682 -2.49212682 -2.46615326]
 [-2.49212682 -2.46615326 -2.49212682 -2.32394874]
 [-2.32394874 -2.32394874 -2.46615326 -1.71227473]
 [ 1.         -1.71227473 -2.32394874 -1.71227473]
 [ 0.          0.          0.          0.        ]]
[[-2.40202248 -2.33670402 -2.40202248 -2.44121349]
 [-2.44121349 -2.44121349 -2.40202248 -2.46472824]
 [-2.46472824 -2.46472824 -2.44121349 -2.47883701]
 [-2.47883701 -2.47883701 -2.46472824 -2.47883701]
 [-2.40202248 -2.22784007 -2.33670402 -2.33670402]
 [-2.33670402 -2.04640007 -2.22784007 -2.04640007]
 [-2.04640007 -1.74400002 -2.22784007 -2.04640007]
 [-2.22784007 -2.04640007 -2.0